#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# message="$(cat $1)"
# requiredPattern="^(add|build|ci|chore|docs|feat|fix|perf|refactor|style|test|revert|merge) .*$"
# if ! [[ $message =~ $requiredPattern ]];
# then
#   echo "-"
#   echo "-"
#   echo "-"
#   echo "🚨 Wrong commit message! 😕"
#   echo "The commit message must have this format:"
#   echo "Your commit message was:"
#   echo $message
#   echo "-"
#   echo "For more information, check script in .husky/commit-msg"
#   echo "-"
#   exit 1
# fi

npm run lint
npx lint-staged
