#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
cat << "EOF"
  ,-.       _,---._ __  / \
 /  )    .-'       `./ /   \
(  (   ,'            `/    /|
 \  `-"             \'\   / |
  `.              ,  \ \ /  |
   /`.          ,'-`----Y   |
  (            ;        |   '
  |  ,-.    ,-'         |  /
  |  | (   |    gw.park | /
  )  |  \  `.___________|/
  `--'   `--'
EOF
npm run lint
npx lint-staged
